name: Create Multiple Files on EC2

on:
  workflow_dispatch:  # 수동 트리거 설정

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Create Files on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "\\
        touch /home/${{ secrets.USERNAME }}/file1.txt ; \\
        touch /home/${{ secrets.USERNAME }}/file2.txt"
